// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function getOptionString(dict, key) {
  return Belt_Option.flatMap(Js_dict.get(dict, key), Js_json.decodeString);
}

function getString(dict, key, $$default) {
  return Belt_Option.getWithDefault(getOptionString(dict, key), $$default);
}

function getStrArrayFromJsonArray(jsonArr) {
  return Belt_Array.keepMap(jsonArr, Js_json.decodeString);
}

function getStrArryFromJson(arr) {
  return Belt_Option.getWithDefault(Belt_Option.map(Js_json.decodeArray(arr), getStrArrayFromJsonArray), []);
}

function getOptionStrArrayFromJson(json) {
  return Belt_Option.map(Js_json.decodeArray(json), getStrArrayFromJsonArray);
}

function getStrArrayFromDict(dict, key, $$default) {
  return Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(dict, key), getOptionStrArrayFromJson), $$default);
}

export {
  getOptionString ,
  getString ,
  getStrArrayFromJsonArray ,
  getStrArryFromJson ,
  getOptionStrArrayFromJson ,
  getStrArrayFromDict ,
  
}
/* No side effect */
