// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Icon$RescriptReactTemplate from "../Icon.bs.js";

function Search$CatagoryItem(Props) {
  var catagory = Props.catagory;
  var setCatagory = Props.setCatagory;
  var selected = Props.selected;
  var match = React.useState(function () {
        return false;
      });
  var setHover = match[1];
  var hover = match[0];
  var lineItem;
  switch (catagory) {
    case /* Stays */0 :
        lineItem = "Stays";
        break;
    case /* Experience */1 :
        lineItem = "Experiences";
        break;
    case /* Online */2 :
        lineItem = "Online Experiences";
        break;
    
  }
  var isSelected = catagory === selected;
  return React.createElement("div", {
              className: "font-light text-base relative cursor-pointer ",
              onClick: (function (param) {
                  return Curry._1(setCatagory, (function (param) {
                                return catagory;
                              }));
                }),
              onMouseEnter: (function (param) {
                  return Curry._1(setHover, (function (param) {
                                return true;
                              }));
                }),
              onMouseLeave: (function (param) {
                  return Curry._1(setHover, (function (param) {
                                return false;
                              }));
                })
            }, lineItem, React.createElement("div", {
                  className: "absolute h-[2px] origin-center mt-1",
                  style: {
                    background: hover ? "#222222" : "",
                    width: hover ? "100%" : "0",
                    transition: hover ? "width .3s ease, background-color .3s ease" : "",
                    transform: hover ? "scaleX(1)" : ""
                  }
                }), isSelected ? React.createElement("div", {
                    className: "absolute h-[2px] bg-[#222222] w-full mt-1"
                  }) : null);
}

var CatagoryItem = {
  make: Search$CatagoryItem
};

function Search(Props) {
  var openSearch = Props.openSearch;
  var setOpenSearch = Props.setOpenSearch;
  var catagory = Props.catagory;
  var setCatagory = Props.setCatagory;
  var match = React.useState(function () {
        return false;
      });
  var setHide = match[1];
  var hide = match[0];
  React.useEffect((function () {
          setTimeout((function (param) {
                  return Curry._1(setHide, (function (prev) {
                                return !prev;
                              }));
                }), 400);
          
        }), [openSearch]);
  return React.createElement(React.Fragment, undefined, hide ? React.createElement("div", {
                    className: "hidden sm:flex flex-row p-2 border border-[#dddddd] rounded-full gap-5 text-sm h-12 cursor-pointer shadow shadow-[#000000]/10 hover:shadow-md transition-shadow w-max xl:w-auto",
                    style: {
                      opacity: openSearch ? "0" : "1",
                      transition: openSearch ? "transform 400ms ease, opacity 0.4s ease" : "",
                      transform: openSearch ? " scale(2.2, 1.8)" : ""
                    },
                    onClick: (function (param) {
                        return Curry._1(setOpenSearch, (function (param) {
                                      return true;
                                    }));
                      })
                  }, React.createElement("div", {
                        className: "font-medium pl-3 self-center"
                      }, "Anywhere"), React.createElement("div", {
                        className: "h-auto w-[1px] bg-[#dddddd]"
                      }), React.createElement("div", {
                        className: "font-medium self-center"
                      }, "Any week"), React.createElement("div", {
                        className: "h-auto w-[1px] bg-[#dddddd]"
                      }), React.createElement("div", {
                        className: "flex flex-row gap-2"
                      }, React.createElement("div", {
                            className: "text-[#717171] font-light self-center pr-1"
                          }, "Add guests"), React.createElement("div", {
                            className: " h-7 w-7 bg-[#fe385c] rounded-full flex justify-center items-center"
                          }, React.createElement(Icon$RescriptReactTemplate.make, {
                                name: "search",
                                size: 15,
                                width: 12,
                                className: "text-white"
                              })))) : null, !hide && openSearch ? React.createElement("div", {
                    className: "hidden sm:flex flex-col",
                    style: {
                      opacity: hide ? "0" : "1",
                      transition: hide ? "transform 400ms ease, opacity 0.4s ease" : ""
                    }
                  }, React.createElement("div", {
                        className: "flex flex-row gap-6 "
                      }, React.createElement(Search$CatagoryItem, {
                            catagory: /* Stays */0,
                            setCatagory: setCatagory,
                            selected: catagory
                          }), React.createElement(Search$CatagoryItem, {
                            catagory: /* Experience */1,
                            setCatagory: setCatagory,
                            selected: catagory
                          }), React.createElement(Search$CatagoryItem, {
                            catagory: /* Online */2,
                            setCatagory: setCatagory,
                            selected: catagory
                          }))) : null, React.createElement("div", {
                  className: "flex sm:hidden w-full flex-row p-2 border border-[#dddddd] rounded-full gap-6 text-sm h-14 cursor-pointer shadow shadow-[#000000]/10 items-center px-3 text-[#4e4e4e]"
                }, React.createElement("div", {
                      className: "flex flex-row justify-between items-center w-full"
                    }, React.createElement("div", {
                          className: "flex flex-row gap-4 justify-center items-center"
                        }, React.createElement(Icon$RescriptReactTemplate.make, {
                              name: "search",
                              size: 18,
                              className: "text-[#4e4e4e]"
                            }), React.createElement("div", {
                              className: "flex flex-col"
                            }, React.createElement("div", {
                                  className: "font-semibold"
                                }, "Anywhere"), React.createElement("div", {
                                  className: "flex flex-row gap-1 text-xs font-[#797979]"
                                }, React.createElement("div", {
                                      className: "font-light"
                                    }, "Any week"), React.createElement("div", {
                                      className: "font-semibold"
                                    }, "•"), React.createElement("div", {
                                      className: "font-light"
                                    }, "Add guests")))), React.createElement("div", undefined, React.createElement("div", {
                              className: "h-10 w-10 border border-[#dddddd] rounded-full flex justify-center items-center"
                            }, React.createElement(Icon$RescriptReactTemplate.make, {
                                  name: "filter",
                                  size: 16,
                                  className: "text-black"
                                }))))));
}

var make = Search;

export {
  CatagoryItem ,
  make ,
  
}
/* react Not a pure module */
