// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Footer$RescriptReactTemplate from "./Components/Footer.bs.js";
import * as NavBar$RescriptReactTemplate from "./Components/NavBar.bs.js";
import * as Filters$RescriptReactTemplate from "./Components/Filters.bs.js";
import * as ViewStays$RescriptReactTemplate from "./ViewStays.bs.js";
import * as FilterUtils$RescriptReactTemplate from "./Utilities/FilterUtils.bs.js";

function App(Props) {
  var match = React.useState(function () {
        return false;
      });
  var openProfile = match[0];
  var match$1 = React.useState(function () {
        return Caml_array.get(FilterUtils$RescriptReactTemplate.filters, 0).type_;
      });
  var selected = match$1[0];
  return React.createElement("div", {
              className: "flex flex-col font-fig-tree"
            }, React.createElement("div", {
                  className: "flex flex-col sticky top-0 z-10 bg-white"
                }, React.createElement(NavBar$RescriptReactTemplate.make, {
                      openProfile: openProfile,
                      setOpenProfile: match[1]
                    }), React.createElement(Filters$RescriptReactTemplate.make, {
                      openProfile: openProfile,
                      selected: selected,
                      setSelected: match$1[1]
                    })), React.createElement(ViewStays$RescriptReactTemplate.make, {
                  selected: selected
                }), React.createElement(Footer$RescriptReactTemplate.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
