// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NavBar$RescriptReactTemplate from "./NavBar.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: "flex flex-col font-fig-tree"
            }, React.createElement(NavBar$RescriptReactTemplate.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
