// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Icon$RescriptReactTemplate from "./Icon.bs.js";
import * as FilterUtils$RescriptReactTemplate from "./FilterUtils.bs.js";

function Filters$FilterItem(Props) {
  var item = Props.item;
  var selected = Props.selected;
  var setSelected = Props.setSelected;
  var openProfile = Props.openProfile;
  var match = React.useState(function () {
        return false;
      });
  var setHover = match[1];
  var hover = match[0];
  return React.createElement("div", {
              className: "flex flex-col cursor-pointer min-w-fit transition-opacity mt-3 items-center relative gap-2 " + (
                selected === item.type_ ? "" : "hover:opacity-100 opacity-50"
              ) + "\n          " + (
                openProfile ? "z-[-2]" : ""
              ) + "\n          ",
              onClick: (function (param) {
                  return Curry._1(setSelected, (function (param) {
                                return item.type_;
                              }));
                }),
              onMouseEnter: (function (param) {
                  return Curry._1(setHover, (function (param) {
                                return true;
                              }));
                }),
              onMouseLeave: (function (param) {
                  return Curry._1(setHover, (function (param) {
                                return false;
                              }));
                })
            }, item.icon, React.createElement("div", {
                  className: "font-semibold text-xs"
                }, item.name), selected === item.type_ || hover ? React.createElement("div", {
                    className: "absolute h-[2px] bg-[#222222] w-full bottom-0 " + (
                      hover && selected !== item.type_ ? "opacity-50" : ""
                    )
                  }) : null);
}

var FilterItem = {
  make: Filters$FilterItem
};

function Filters(Props) {
  var openProfile = Props.openProfile;
  var match = React.useState(function () {
        return Caml_array.get(FilterUtils$RescriptReactTemplate.filters, 0).type_;
      });
  var setSelected = match[1];
  var selected = match[0];
  return React.createElement("div", {
              className: " hidden sm:flex flex-row border h-20 w-full shadow-sm px-5 md:px-10 lg:px-16"
            }, React.createElement("div", {
                  className: "flex flex-row gap-8 w-[90%] overflow-x-scroll"
                }, FilterUtils$RescriptReactTemplate.filters.map(function (item) {
                      return React.createElement(Filters$FilterItem, {
                                  item: item,
                                  selected: selected,
                                  setSelected: setSelected,
                                  openProfile: openProfile
                                });
                    })), React.createElement("div", {
                  className: " w-[10%] m-auto flex justify-end "
                }, React.createElement("div", {
                      className: "flex flex-row justify-center border border-[#dddddd] rounded-xl w-fit p-4 gap-3 items-center cursor-pointer"
                    }, React.createElement(Icon$RescriptReactTemplate.make, {
                          name: "filter",
                          size: 14,
                          className: "text-[#222222]"
                        }), React.createElement("div", {
                          className: "text-xs font-medium text-[#222222]"
                        }, "Filters"))));
}

var make = Filters;

export {
  FilterItem ,
  make ,
  
}
/* react Not a pure module */
