// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Icon$RescriptReactTemplate from "./Icon.bs.js";

function Footer(Props) {
  var match = React.useState(function () {
        return /* Explore */0;
      });
  var setMode = match[1];
  var mode = match[0];
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "h-auto w-screen absolute bottom-0 p-2 px-5 md:px-10 lg:px-16 border bordet-t-[#ebebeb] hidden md:flex flex-row justify-between"
                }, React.createElement("div", {
                      className: "text-sm font-light text-[#585858]"
                    }, "© 2023 Airbnb Clone, Inc.  ·  Privacy  ·  Terms  ·  Sitemap  ·  Company details"), React.createElement("div", {
                      className: "flex flex-row gap-4 text-medium text-sm items-center"
                    }, React.createElement(Icon$RescriptReactTemplate.make, {
                          name: "world",
                          size: 16
                        }), React.createElement("div", {
                          className: "hover:underline"
                        }, "English (IN)"), React.createElement("div", {
                          className: "hover:underline"
                        }, "₹ INR"), React.createElement("div", {
                          className: "hover:underline"
                        }, "Support & resources"))), React.createElement("div", {
                  className: "h-16 w-screen absolute bottom-0 p-2 px-5 md:px-10 lg:px-16 border bordet-t-[#ebebeb] flex md:hidden flex-row gap-10 justify-center items-center"
                }, React.createElement("div", {
                      className: "flex flex-col gap-2 items-center justify-center",
                      onClick: (function (param) {
                          return Curry._1(setMode, (function (param) {
                                        return /* Explore */0;
                                      }));
                        })
                    }, React.createElement(Icon$RescriptReactTemplate.make, {
                          name: "search-2",
                          size: 25,
                          className: mode === /* Explore */0 ? "text-[#ff385c]" : ""
                        }), React.createElement("div", {
                          className: "text-xs  " + (
                            mode === /* Explore */0 ? "text-[#222222] font-semibold" : "text-[#717171] font-medium"
                          )
                        }, "Explore")), React.createElement("div", {
                      className: "flex flex-col gap-2 items-center justify-center",
                      onClick: (function (param) {
                          return Curry._1(setMode, (function (param) {
                                        return /* Wishlists */1;
                                      }));
                        })
                    }, React.createElement(Icon$RescriptReactTemplate.make, {
                          name: "heart",
                          size: 25,
                          className: mode === /* Wishlists */1 ? "text-[#ff385c]" : ""
                        }), React.createElement("div", {
                          className: "text-xs " + (
                            mode === /* Wishlists */1 ? "text-[#222222] font-semibold" : "text-[#717171] font-medium"
                          )
                        }, "Wishlists")), React.createElement("div", {
                      className: "flex flex-col gap-2 items-center justify-center",
                      onClick: (function (param) {
                          return Curry._1(setMode, (function (param) {
                                        return /* LogIn */2;
                                      }));
                        })
                    }, React.createElement(Icon$RescriptReactTemplate.make, {
                          name: "profile",
                          size: 25,
                          className: mode === /* LogIn */2 ? "text-[#ff385c]" : ""
                        }), React.createElement("div", {
                          className: "text-xs " + (
                            mode === /* LogIn */2 ? "text-[#222222] font-semibold" : "text-[#717171] font-medium"
                          )
                        }, "Log In"))));
}

var make = Footer;

export {
  make ,
  
}
/* react Not a pure module */
