// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Icon(Props) {
  var name = Props.name;
  var sizeOpt = Props.size;
  var widthOpt = Props.width;
  var className = Props.className;
  var iconTypeOpt = Props.iconType;
  var onClick = Props.onClick;
  var size = sizeOpt !== undefined ? sizeOpt : 20;
  var width = widthOpt !== undefined ? widthOpt : size;
  var iconType = iconTypeOpt !== undefined ? iconTypeOpt : "app";
  var otherClasses = className !== undefined ? className : "";
  var tmp = {
    className: "fill-current " + otherClasses,
    height: String(size) + "px",
    width: String(width) + "px"
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("svg", tmp, React.createElement("use", {
                  xlinkHref: "/icons/" + iconType + ".svg#" + name
                }));
}

var make = Icon;

export {
  make ,
  
}
/* react Not a pure module */
