// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Icon$RescriptReactTemplate from "./Icon.bs.js";
import * as Search$RescriptReactTemplate from "./Search.bs.js";
import * as AirbnbSvg$RescriptReactTemplate from "./AirbnbSvg.bs.js";
import * as OutsideClick$RescriptReactTemplate from "./Utilities/OutsideClick.bs.js";

function NavBar$ProfileItem(Props) {
  var item = Props.item;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "font-light";
  return React.createElement("div", {
              className: "p-3 px-5 pr-24 hover:bg-[#f7f7f7] w-full text-[#222222] " + className
            }, item);
}

var ProfileItem = {
  make: NavBar$ProfileItem
};

function NavBar(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setOpenProfile = match[1];
  var openProfile = match[0];
  var profileRef = React.useRef(null);
  OutsideClick$RescriptReactTemplate.useOutsideClick({
        TAG: /* ArrayOfRef */0,
        _0: [profileRef]
      }, undefined, openProfile, undefined, (function (param) {
          return Curry._1(setOpenProfile, (function (x) {
                        return !x;
                      }));
        }), undefined);
  return React.createElement("div", {
              className: "sticky h-20 border border-b-[#ebebeb] px-5 md:px-10 lg:px-16 flex items-center justify-between"
            }, React.createElement("div", {
                  className: "text-[#fe385c] xl:w-1/3 hidden md:flex"
                }, AirbnbSvg$RescriptReactTemplate.bnbwithtext), React.createElement("div", {
                  className: "text-[#fe385c] xl:w-1/3 hidden md:hidden sm:flex"
                }, AirbnbSvg$RescriptReactTemplate.bnblogo), React.createElement(Search$RescriptReactTemplate.make, {}), React.createElement("div", {
                  className: "hidden sm:flex flex-row xl:w-1/3  justify-end"
                }, React.createElement("div", {
                      className: "font-medium text-sm flex flex-row gap-2 items-center cursor-pointer"
                    }, React.createElement("div", {
                          className: "h-11 hidden xl:flex hover:bg-[#f7f7f7] rounded-full p-4  transition-colors items-center justify-center"
                        }, "Airbnb your home"), React.createElement("div", {
                          className: "h-11 hidden lg:flex hover:bg-[#f7f7f7] rounded-full p-4 transition-colors items-center justify-center"
                        }, React.createElement(Icon$RescriptReactTemplate.make, {
                              name: "world",
                              size: 16
                            })), React.createElement("div", {
                          className: "flex flex-row gap-1 md:gap-3 p-1 px-2 ml-2 pl-3 border border-[#dddddd] rounded-full h-11 shadow-[#000000]/10 hover:shadow-md transition-shadow items-center justify-center",
                          onClick: (function (param) {
                              return Curry._1(setOpenProfile, (function (prev) {
                                            return !prev;
                                          }));
                            })
                        }, React.createElement(Icon$RescriptReactTemplate.make, {
                              name: "hamburger",
                              size: 16,
                              className: "text-[#222222] "
                            }), React.createElement(Icon$RescriptReactTemplate.make, {
                              name: "avatar",
                              size: 29,
                              className: "text-[#717171]"
                            }), openProfile ? React.createElement("div", {
                                ref: profileRef,
                                className: "flex bg-white flex-col absolute top-16 right-16 rounded-xl h-auto transition-shadow items-center justify-center min-w-max py-2 mt-2",
                                style: {
                                  boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px"
                                }
                              }, React.createElement(NavBar$ProfileItem, {
                                    item: "Sign up",
                                    className: "font-semibold"
                                  }), React.createElement(NavBar$ProfileItem, {
                                    item: "Log in"
                                  }), React.createElement("div", {
                                    className: "w-full h-[1px] bg-[#dddddd] my-2"
                                  }), React.createElement(NavBar$ProfileItem, {
                                    item: "Airbnb your home"
                                  }), React.createElement(NavBar$ProfileItem, {
                                    item: "Host an experience"
                                  }), React.createElement(NavBar$ProfileItem, {
                                    item: "Help"
                                  })) : null))));
}

var make = NavBar;

export {
  ProfileItem ,
  make ,
  
}
/* react Not a pure module */
