// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Icon$RescriptReactTemplate from "./Icon.bs.js";

function Search(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "hidden sm:flex flex-row p-2 border border-[#dddddd] rounded-full gap-5 text-sm h-12 cursor-pointer shadow shadow-[#000000]/10 hover:shadow-md transition-shadow w-max xl:w-auto"
                }, React.createElement("div", {
                      className: "font-medium pl-3 self-center"
                    }, "Anywhere"), React.createElement("div", {
                      className: "h-auto w-[1px] bg-[#dddddd]"
                    }), React.createElement("div", {
                      className: "font-medium self-center"
                    }, "Any week"), React.createElement("div", {
                      className: "h-auto w-[1px] bg-[#dddddd]"
                    }), React.createElement("div", {
                      className: "flex flex-row gap-2"
                    }, React.createElement("div", {
                          className: "text-[#717171] font-light self-center pr-1"
                        }, "Add guests"), React.createElement("div", {
                          className: " h-7 w-7 bg-[#fe385c] rounded-full flex justify-center items-center"
                        }, React.createElement(Icon$RescriptReactTemplate.make, {
                              name: "search",
                              size: 15,
                              width: 12,
                              className: "text-white"
                            })))), React.createElement("div", {
                  className: "flex sm:hidden w-full flex-row p-2 border border-[#dddddd] rounded-full gap-6 text-sm h-14 cursor-pointer shadow shadow-[#000000]/10 items-center px-3 text-[#4e4e4e]"
                }, React.createElement("div", {
                      className: "flex flex-row justify-between items-center w-full"
                    }, React.createElement("div", {
                          className: "flex flex-row gap-4 justify-center items-center"
                        }, React.createElement(Icon$RescriptReactTemplate.make, {
                              name: "search",
                              size: 18,
                              className: "text-[#4e4e4e]"
                            }), React.createElement("div", {
                              className: "flex flex-col"
                            }, React.createElement("div", {
                                  className: "font-semibold"
                                }, "Anywhere"), React.createElement("div", {
                                  className: "flex flex-row gap-1 text-xs font-[#797979]"
                                }, React.createElement("div", {
                                      className: "font-light"
                                    }, "Any week"), React.createElement("div", {
                                      className: "font-semibold"
                                    }, "•"), React.createElement("div", {
                                      className: "font-light"
                                    }, "Add guests")))), React.createElement("div", undefined, React.createElement("div", {
                              className: "h-10 w-10 border border-[#dddddd] rounded-full flex justify-center items-center"
                            }, React.createElement(Icon$RescriptReactTemplate.make, {
                                  name: "filter",
                                  size: 16,
                                  className: "text-black"
                                }))))));
}

var make = Search;

export {
  make ,
  
}
/* react Not a pure module */
